export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            "colors": {
                "inverse-on-surface": "#eaf1ff",
                "primary": "#00355f",
                "primary-fixed": "#d2e4ff",
                "tertiary-container": "#9a000d",
                "error-container": "#ffdad6",
                "on-tertiary": "#ffffff",
                "on-secondary": "#ffffff",
                "surface-container-high": "#dfe9fa",
                "on-secondary-fixed-variant": "#005137",
                "on-primary-fixed": "#001c37",
                "secondary-fixed": "#85f8c4",
                "background": "#f8f9ff",
                "secondary": "#006c4a",
                "secondary-fixed-dim": "#68dba9",
                "outline-variant": "#c2c7d1",
                "on-secondary-fixed": "#002114",
                "inverse-primary": "#a0c9ff",
                "on-error": "#ffffff",
                "on-tertiary-container": "#ffa297",
                "tertiary": "#6f0006",
                "surface-bright": "#f8f9ff",
                "surface-container": "#e5eeff",
                "surface-variant": "#d9e3f4",
                "surface": "#f8f9ff",
                "on-primary": "#ffffff",
                "tertiary-fixed": "#ffdad6",
                "inverse-surface": "#27313e",
                "tertiary-fixed-dim": "#ffb4ab",
                "outline": "#727780",
                "on-secondary-container": "#00714e",
                "secondary-container": "#82f5c1",
                "surface-container-lowest": "#ffffff",
                "on-surface-variant": "#42474f",
                "error": "#ba1a1a",
                "surface-dim": "#d1dbec",
                "primary-fixed-dim": "#a0c9ff",
                "on-primary-fixed-variant": "#07497d",
                "on-background": "#121c28",
                "surface-tint": "#2d6197",
                "primary-container": "#0f4c81",
                "on-surface": "#121c28",
                "on-primary-container": "#8ebdf9",
                "surface-container-highest": "#d9e3f4",
                "on-tertiary-fixed": "#410002",
                "on-tertiary-fixed-variant": "#93000b",
                "surface-container-low": "#eef4ff",
                "on-error-container": "#93000a"
            },
            fontFamily: {
                headline: ["Manrope", "sans-serif"],
                body: ["IBM Plex Sans Arabic", "sans-serif"],
                label: ["IBM Plex Sans Arabic", "sans-serif"],
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
        },
    },
    plugins: [],
};
